=head1 lastpass2keepass

Allows you to convert the LastPass export to a KeePass XML import.

=head1 DESCRIPTION

Allows you to convert the LastPass export to a KeePass XML import.

=head2 REQUIRES

=over

=item * Python 2.6 (sys, csv, time, datetime, lxml)

=back

=head2 SUPPORTS

=over

=item * KeePassXML

=back

=head2 USAGE

	python lastpass2keepass.py export keepass.xml

=head1 ACKNOWLEDGEMENTS

I<Python XML processing with lxml>, I<John W. Shipman>, L<http://infohost.nmt.edu/tcc/help/pubs/pylxml/>.

=head1 AVAILABILITY

The latest version of pydns can be found at: L<http://github.com/nazariuskappertaal/pydns>.

=head1 COPYRIGHT

Copyright 2010, Anirudh Joshi: L<nazariuskappertaal@gmail.com|mailto:nazariuskappertaal@gmail.com>.

This program is free software: you can redistribute it and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation, either version 3 of the License, or (at your option) any later 
version.

You should have received a copy of the GNU General Public License along with 
this program. If not, see L<http://www.gnu.org/licenses/>.

=head1 WARRANTY

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

